
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:7777"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: cms-service
          uri: http://cms-service:7070
          predicates:
            - Path=/api/courses/**
        - id: cms-service
          uri: http://cms-service:7070
          predicates:
            - Path=/api/grades/**
        - id: cms-service
          uri: http://cms-service:7070
          predicates:
            - Path=/api/programmes/**
        - id: ums
          uri: http://ums-service:7071
          predicates:
            - Path=/api/teachers/**
        - id: ums
          uri: http://ums-service:7071
          predicates:
            - Path=/api/auth/**
      enabled: true
