server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0